# Generated by Django 2.1.3 on 2019-01-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocuSignConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('accesstoken', models.CharField(max_length=500)),
                ('account_id', models.CharField(max_length=200)),
                ('account_username', models.CharField(max_length=200)),
                ('redirecturl', models.URLField()),
                ('baseurl', models.URLField()),
                ('integratorkey', models.CharField(max_length=200)),
                ('oauthbaseurl', models.URLField()),
                ('clientid', models.CharField(default='123', max_length=200)),
                ('authmethod', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IPFSConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(verbose_name='IPFS Server IP Address')),
            ],
        ),
    ]
