# Generated by Django 2.1.3 on 2019-01-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipfsconfiguration',
            name='port',
            field=models.CharField(default=5000, max_length=10),
        ),
    ]
