"""
Django settings for djcreativetim project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'cq6fjom4^0d$nqz^43^z)yxlwk2=kvya%&ow(s8v9tgdt=qups'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contracts',
    'Configuration'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djcreativetim.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djcreativetim.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/'

DOCU_USER_NAME = 'pomkar65@gmail.com'
DOCU_ACCESS_TOKEN = 'eyJ0eXAiOiJNVCIsImFsZyI6IlJTMjU2Iiwia2lkIjoiNjgxODVmZjEtNGU1MS00Y2U5LWFmMWMtNjg5ODEyMjAzMzE3In0.AQkAAAABAAUABwCAfXt3IHnWSAgAgL2ehWN51kgCAPbxg3IXSnxFhOQoi3ureokVAAEAAAAYAAEAAAAFAAAADQAkAAAAZjBmMjdmMGUtODU3ZC00YTcxLWE0ZGEtMzJjZWNhZTNhOTc4EgABAAAACwAAAGludGVyYWN0aXZlMACAIxl1IHnWSA.WT7KtFYjiK1JMxtofj9oa6pZqU6Li-ZyFShWwqubNpG9raXvct2Hurtq2vdgBnp3VxVv3NmviCMulu9Vn7o9DUDXwumx828wp4oPmCwOFNkT07IoX8QontAnzjg0BCuB9jXQWv6gjN1x-qvXoj1ZFmKpbCIGLE8J-0LGvJNi7NqyIS6gaJ2mqyWMTEyO6FjaEiz5K4NdnKxuYdbcS3rJbh9y6ff8I6gB9UF4Swt7inyc528sbSOew_QDXNQgiukznr_FucwRrDkNYbV3W7dv-0JxKN2AsHGHejmNaIZ6Gba6X0ktMFYLBfp3WjXbxpBZs8xULq6MosWm6mqMU04o2Q'
DOCU_ACCOUNT_ID = '46e64279-17eb-4695-81f4-5bc5fb414ee1'
DOCU_ACCOUNT_USERNAME = '7283f1f6-4a17-457c-84e4-288b7bab7a89'
DOCU_REDIRECT_URL = 'http://localhost:8000/redirect_api/'
DOCU_BASE_URL = 'https://demo.docusign.net/restapi'
DOCU_INTEGRATOR_KEY = '0f9c09f8-d8b0-41cc-9afc-ebe614418101'
DOCU_OAUTH_BASE_URL = "account-d.docusign.com"
DOCU_PRIVATE_KEY = os.path.join(BASE_DIR, 'keys', 'private_key')
DOCU_CLIENT_ID = '123'
DOCU_AUTH_METHOD = 'None'

BLOCKCHAINURL = 'http://3.88.70.56:3001/createContract'

#https://account-d.docusign.com/oauth/auth?response_type=code&client_id=0f9c09f8-d8b0-41cc-9afc-ebe614418101&scope=signature impersonation&redirect_uri=http://34.201.57.61/redirect_api/
